.PHONY: clean All

All:
	@echo "----------Building project:[ Callenge - Debug ]----------"
	@cd "Callenge" && "$(MAKE)" -f  "Callenge.mk"
clean:
	@echo "----------Cleaning project:[ Callenge - Debug ]----------"
	@cd "Callenge" && "$(MAKE)" -f  "Callenge.mk" clean
